---
env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
parser: babel-eslint
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
